import "./globals.css";
import Navbar from "../app/_components/navbar";
import Footer from "../app/_components/footer";

export const metadata = {
  title: "Notes App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main>{children}</main>

        <Footer/>
      </body>
    </html>
  );
}
